### ISSUE TITLE
Adding credentials for private maven repository

### ISSUE THREAD

**Issue by shaulzorea** [almond-sh/almond#100]
Hi there,

I have a private maven repository protected by a password from which I'd like to import dependencies.
classpath has a addRepository method however I don't see a way to specify its credentials.
Is that possible? If not, is there a workaround

Much thanks,
Shaul.

**Comment by alexarchambault** [comment]
This now works as in [Ammonite](http://ammonite.io/#Ammonite-REPL), look for "authentication" on [this page](http://ammonite.io/#Ammonite-REPL).

**Comment by shaulzorea** [comment]
Great, thanks for the update.
