### ISSUE TITLE
Turn off printing of variables after cell execution

### ISSUE THREAD

**Issue by tdomhan** [almond-sh/almond#101]
Hi,
is there any way I turn off that the variables are printed after each cell is executed? My variables will often result in very long and unnecessary print statements.
Thanks a lot!

**Comment by tdomhan** [comment]
My solution for now is to just limit it to one line per variable:
`pprintConfig = pprintConfig.copy(height=1)`

**Comment by AlecZorab** [comment]
This is a killer for me. If you're working with large collections of ADTs, it can quickly get to the point where executing anything at all becomes prohibitively slow.

**Comment by AlecZorab** [comment]
As a nuclear option, you can define the following, although you'll love prettyprinting completely

```scala
implicit def dont_show_stuff[T] = new pprint.PPrinter[T]{
    def render0(t:T, c: pprint.Config) : Iterator[String] = List("[Not Shown]").toIterator
}
```

**Comment by alexarchambault** [comment]
This should now work exactly as in Ammonite (results should already be truncated, and things can be tweaked via the pprint config as you did).
