### ISSUE TITLE
question: how to import code from an external module

### ISSUE THREAD

**Issue by AngryMaciek** [almond-sh/almond#1021]
Im a rather newbie in _Scala_ but I was wondering if there is a mechanism to import classess, functions I have in an external text file (not in the same directory)? Would be a very useful feature as defining hundreds of code lines in a notebook impairs brevity, better to put them out in a separate file and just "load" in the nb.

**Comment by samuelsayag** [comment]
Hello @AngryMaciek ,
From what I see the kernel almond is based largely on Ammonite (https://ammonite.io/#Ammonite) which is a kind of improved REPL for Scala that you can use even without Almond.
The documentation shows how to make import in an Ammonite session as well as how to reference new repo:
- https://ammonite.io/#import$ivy
- https://ammonite.io/#import$repo

I tested it in a jupyter Lab and it works. The thing I don't quite understand from ammonite documentation is the resolution of local jars.
In principle, you should have them all under: `~/.ivy2/cache`
But I can see that with `coursier` installed most of my jars go to  `~.cache/coursier/v1/https/repo1.maven.org/maven2` for instance for jar that I downloaded from maven.
I don't quite know how the resolution is done but I guess Ammonite fetch from coursier that fetcher from its cache maybe.

For instance for me it is sufficient to do this from a notebook:
```
import $ivy.`com.typesafe.akka::akka-actor:2.6.20`
import akka.util.ByteString
val b = ByteString("Hello world!")
```
and this will not fill my `.ivy2/cache` with a new jar but rather will use the one from the coursier cache. So I guess Ammonite kind of ask via `$ivy` for the jar to coursier that does the resolution.

**Comment by AngryMaciek** [comment]
Hi @samuelsayag,

I am not really a _Scala_ developer so I do not know the meaning of these words: _ivy_, _coursier_, _maven_.

However, I am not sure if your post above does answer my initial question - how to include my own custom piece of code from another directory. Will that be possible with the mechanisms you mentioned?

**Comment by sbrunk** [comment]
@AngryMaciek you can import Ammonite scripts which are essentially Scala files:

i.e. create a file `/some/dir/script.sh` with some code:
```scala
val x = 42
```

Then in a notebook load that script:
```
repl.load.exec(os.Path("/some/dir/script.sc"))
```

Now you should be able to access `x` in subsequent cells.

You could also use paths relative to your working dir, i.e.:
```
repl.load.exec(os.pwd / os.up / "script.sc")
```

**Comment by AngryMaciek** [comment]
Thank you @sbrunk! I will test it out next week and come back here.

**Comment by AngryMaciek** [comment]
That works, thank you!
