### ISSUE TITLE
Plan for scala friendly editor formatting

### ISSUE THREAD

**Issue by dazebug** [almond-sh/almond#107]
Hello!

I use jupyter-scala almost every time in my workspace (thank you) but some of editor features annoying me.

Everytime I 'enter' after some brace's opened, it appears a lot of tabs on my cursor.
For example,

``` scala
val someVal = Seq(1, 2, 3, 4).map { n =>
                                  |
```

instead of

``` scala
val someVal = Seq(1, 2, 3, 4).map { n =>
  |
```

Do you have any plan for scala-friendly editor features? or did I miss some feature from others?

**Comment by alexarchambault** [comment]
It works as in your second example, since some time already (jupyter >= 5.7.0 at least, probably for earlier versions too).
