### ISSUE TITLE
Add authenticated repository 

### ISSUE THREAD

**Issue by evacchi** [almond-sh/almond#109]
Would it possible to specify an authenticated maven repository ? I couldn't find a mention for it

thanks!

**Comment by mliberty** [comment]
Any update on this? Thanks!

**Comment by mliberty** [comment]
This worked for for me

`classpath.addRepository("https://user:pass@company.com/repo")`

**Comment by rtimush** [comment]
With the latest version you can add authenticated repositories:
https://github.com/alexarchambault/ammonium/pull/82/files#diff-cae375689c89089aa609103bd132b4b1R209

There is though an issue with spark, see https://github.com/alexarchambault/jupyter-scala/pull/152

**Comment by alexarchambault** [comment]
This now works as in [Ammonite](http://ammonite.io/#Ammonite-REPL), look for "authentication" on [this page](http://ammonite.io/#Ammonite-REPL).
