### ISSUE TITLE
Support for Scala 2.12

### ISSUE THREAD

**Issue by Bachenbenno** [almond-sh/almond#110]
Hi there!

Scala 2.12 just got released. Would you consider adding support for it? Thanks in advance!

Best regards,
Sebastian

**Comment by alexarchambault** [comment]
jupyter-scala rests on (a fork of) ammonite, so it would need Ammonite itself to get support for 2.12 first.

**Comment by Bachenbenno** [comment]
OK, I see. Guess I'll have to be patient then :-)

**Comment by mslinn** [comment]
[Ammonite 0.8.1](http://www.lihaoyi.com/Ammonite/#0.8.1) has been released for Scala 2.12.1

**Comment by dazebug** [comment]
Did anybody try to compile in 2.12? Does it work?

**Comment by mslinn** [comment]
@dazebug I did not try to compile with Scala 2.12. However, Apache Spark is not available for Scala 2.12, and probably will not be available for a while.

**Comment by ryan-williams** [comment]
current instructions for compiling to 2.12, afaict:

- `cd` to root of this repo
- [set version in `jupyter-scala` to `2.12.2`](https://github.com/jupyter-scala/jupyter-scala/blob/98bac7034f07e3e51d101846953aecbdb7a4bb5d/jupyter-scala#L6)
  - `perl -pi -e 's/2\.11\.11/2.12.2/' jupyter-scala`
- install as normal: `./jupyter-scala`

**Comment by cloudbow** [comment]
Is there a Jupyter version which has this in it?

**Comment by alexarchambault** [comment]
Current master, and all releases under the "almond" name, support scala 2.12.
