### ISSUE TITLE
Is Coursier automatically installed?

### ISSUE THREAD

**Issue by mslinn** [almond-sh/almond#121]
The Jupyter-Scala documentation says that Coursier must be manually installed. I suspect that Coursier is a dependency that gets installed automatically along with Jupyter-Scala. Can anyone confirm or deny?

**Comment by MDMBD** [comment]
Hello,
I cannot install the kernel scala (via coursier) on my VM centos7.
Here are the error messages.

If I play this :
 [   ~]$ curl -L -o coursier https://git.io/vgvpD
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100   122  100   122    0     0     70      0  0:00:01  0:00:01 --:--:--   262
100   133  100   133    0     0     63      0  0:00:02  0:00:02 --:--:--    63
100 11832  100 11832    0     0   4490      0  0:00:02  0:00:02 --:--:-- 23806

[vm4455~]$  exec coursier launch \
>   -r sonatype:releases -r sonatype:snapshots \
>   -i ammonite \
>   -I ammonite:org.jupyter-scala:ammonite-runtime_$SCALA_VERSION:$AMMONIUM_VERSION \
>   -I ammonite:org.jupyter-scala:scala-api_$SCALA_VERSION:$VERSION \
>   org.jupyter-scala:scala-cli_$SCALA_VERSION:$VERSION \
>   -- \
>     --id scala \
>     --name "Scala" \
>     "$@" 
-bash: exec: coursier: not found


If I play this :

$ curl -L -o coursier https://git.io/vgvpD && chmod +x coursier && ./coursier –help

  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100   122  100   122    0     0     69      0  0:00:01  0:00:01 --:--:-- 24400
100   133  100   133    0     0     66      0  0:00:02  0:00:01  0:00:01    66
100 11832  100 11832    0     0   5143      0  0:00:02  0:00:02 --:--:--  5143
Error while downloading https://oss.sonatype.org/content/repositories/releases/io/get-coursier/coursier-cli_2.11/1.0.0-M15/coursier-cli_2.11-1.0.0-M15-standalone.jar: oss.sonatype.org, ignoring it
 [    ~]$ exec coursier launch \
>   -r sonatype:releases -r sonatype:snapshots \
>   -i ammonite \
>   -I ammonite:org.jupyter-scala:ammonite-runtime_$SCALA_VERSION:$AMMONIUM_VERSION \
>   -I ammonite:org.jupyter-scala:scala-api_$SCALA_VERSION:$VERSION \
>   org.jupyter-scala:scala-cli_$SCALA_VERSION:$VERSION \
>   -- \
>     --id scala \
>     --name "Scala" \
>     "$@" 
-bash: exec: coursier: not found

Thank you for your help
Have a good day

**Comment by alexarchambault** [comment]
Manually installed with the current master (don't remember how it was at the time this issue was opened).
