### ISSUE TITLE
Maven classifier

### ISSUE THREAD

**Issue by ech2** [almond-sh/almond#128]
Hi there!

I'm trying to set up a notebook with Stanford's CoreNLP, which contains a dependency with classifier:

```xml
<dependency>
    <groupId>edu.stanford.nlp</groupId>
    <artifactId>stanford-corenlp</artifactId>
    <version>3.7.0</version>
    <classifier>models-english</classifier>
</dependency>
```

I've tried to add it on using the following statement:

```scala
interp.load.ivy("edu.stanford.nlp" % "stanford-corenlp" % "3.7.0" classifier "models-english")
```

but got an error:

```
cmd5.sc:1: value classifier is not a member of (String, String, String)
val res5 = interp.load.ivy("edu.stanford.nlp" % "stanford-corenlp" % "3.7.0" classifier "models-english")
```

Is there any other way to import a dependency with a classifier?

Cheers,
Eugene

**Comment by geastham** [comment]
Bump! I'm trying to transfer an SBT project Spark project to Jupyter notebooks for sharing.

With a running SparkSession, I enter:
```
// Load special ML / NLP libraries via interop
interp.load.ivy("edu.stanford.nlp" % "stanford-corenlp" % "3.6.0")
interp.load.ivy("edu.stanford.nlp" % "stanford-corenlp" % "3.6.0" classifier "models")
```

And get:
```
cmd10.sc:2: value classifier is not a member of (String, String, String)
val res10_1 = interp.load.ivy("edu.stanford.nlp" % "stanford-corenlp" % "3.6.0" classifier "models")
                                                                                ^
```

Any help would be much appreciated.

**Comment by Atry** [comment]
I tried the new fix at https://github.com/lihaoyi/Ammonite/issues/387

``` scala
interp.load.ivy(
  // Directly using coursier API. Can pass in exclusions,
  // attributes, configurations, classifiers, etc.
  coursier.Dependency(
    coursier.Module("net.sf.json-lib", "json-lib"),
    "2.4",
    attributes = coursier.Attributes(classifier = "jdk15")
  ),
  "xom" % "xom" % "1.1"
)
```
It does not work for ammonium 0.8.3-2
```
cmd7.sc:4: type mismatch;
 found   : coursier.Dependency
    (which expands to)  coursier.core.Dependency
 required: (String, String, String)
  coursier.Dependency(
                     ^cmd7.sc:9: type mismatch;
 found   : (String, String, String)
 required: Boolean
  "xom" % "xom" % "1.1"
                ^
```

**Comment by lambdaofgod** [comment]
Hey guys, I was just able to configure my notebook so that it works, maybe someone will find this useful: https://github.com/lambdaofgod/examples-counterexamples/blob/master/notebooks/CoreNLP.ipynb

**Comment by alexarchambault** [comment]
@Atry's example seems to work fine with the current master (and most releases under the "almond" name should be ok too).

**Comment by gneusch** [comment]
@Atry's example unfortunately doesn't work for me. I receive the following error:
`cmd1.sc:4: object Dependency is not a member of package coursier
    coursier.Dependency(
             ^cmd1.sc:5: object Module is not a member of package coursier
      coursier.Module("net.sf.json-lib", "json-lib"),
               ^cmd1.sc:7: not found: value attributes
      attributes = coursier.Attributes(classifier = "jdk15")
      ^Compilation Failed
Compilation Failed`

I imported coursier._ but nothing else. Is it possible that I'm missing an import?
Thanks in advance

**Comment by alexarchambault** [comment]
@gneusch Yeah, the coursier API used from Ammonite changed a bit. The following should now work:
```scala
interp.load.ivy(
  // Directly using coursier API. Can pass in exclusions,
  // attributes, configurations, classifiers, etc.
  coursierapi.Dependency.of("net.sf.json-lib", "json-lib", "2.4").withClassifier("jdk15"),
  "xom" % "xom" % "1.1"
)
```
or even
```scala
interp.load.ivy(
  // Directly using coursier API. Can pass in exclusions,
  // attributes, configurations, classifiers, etc.
  ("net.sf.json-lib" % "json-lib" % "2.4").withClassifier("jdk15"),
  "xom" % "xom" % "1.1"
)
```
