### ISSUE TITLE
Scala Syntax Highlighting Error

### ISSUE THREAD

**Issue by Atry** [almond-sh/almond#131]
I have some code like this:
``` scala
def lossFunction(implicit pair: From[INDArray :: INDArray :: HNil]##T): To[Double]##T = {
    val input = pair.head
    val expectedOutput = pair.tail.head
    abs(myNeuralNetwork.compose(input) - expectedOutput).sum
}
```

Note that `##` is an infix type. `To[Double]##T` has the same meaning as `##[To[Double], T]`.

However, highlighter in `jupyter-scala` renders the two `#` characters in different colors, which is not correct:
https://gist.github.com/Atry/050ca1e9633c39510fa2adf472cbd0a2

**Comment by Atry** [comment]
Another simple expression break the highlighter is`##toString`, which should be compiled as `this.##.toString`

**Comment by rgbkrk** [comment]
Is this currently not highlighting properly in the Jupyter notebook or nteract? If so, we'll want to report it in https://github.com/codemirror/CodeMirror as a Scala syntax highlighting issue.

**Comment by Atry** [comment]
Yes, please.

**Comment by rgbkrk** [comment]
Fixed in code mirror, this can be closed now (only waiting on it to be a part of a jupyter release).
