### ISSUE TITLE
Re-add support for the "-r" CLI option

### ISSUE THREAD

**Issue by mallman** [almond-sh/almond#148]
Older versions of jupyter-scala supported a CLI option `-r` for adding custom artifact resolvers. The new codebase has not ported that functionality over yet. It would be great to have. Right now we get around this limitation by adding our custom resolvers as part of the Jupyter notebook itself. However, I'd like this to be something our end users need not concern themselves with.

Thanks!

**Comment by AlecZorab** [comment]
:+1:
It looks like adding the resolvers in the notebook doesn't propagate into the resolvers used for building spark contexts, so this is currently blocking use of spark for us

**Comment by alexarchambault** [comment]
Current master, and most releases under the "almond" name, have a `--extra-repository` option for that.
