### ISSUE TITLE
Compilation Failed

### ISSUE THREAD

**Issue by washim** [almond-sh/almond#155]
Was trying to execute simple scala from jupyter

val textFile = sc.textFile("daily-minimum-temperatures.csv")
textFile.count()

Which gives following error

cmd0.sc:1: not found: value sc
val textFile = sc.textFile("daily-minimum-temperatures.csv")
               ^
Compilation Failed

**Comment by rgbkrk** [comment]
If you want to use Spark, you'll need to set it up first by [importing the libraries and creating a spark session](https://github.com/alexarchambault/jupyter-scala#spark).

**Comment by washim** [comment]
Thanks, its working fine.
