### ISSUE TITLE
Not a member of error

### ISSUE THREAD

**Issue by izhangzhihao** [almond-sh/almond#156]
At first,create a project use sbt,

```scala
package object apackage {
  type WhatEver = Int
}

package apackage {
  object WhatEver {
    val foo = "bar"
  }
}
```

then write some code to use those code

```scala
object Use extends App {

  import apackage.WhatEver
  import apackage.WhatEver._

  println(WhatEver.foo)
}
```
All code works fine.
But when I run `publishLocal` in sbt , and try use those libs in jupyter scala, error comes!

```scala
import $ivy.`notamemberof::notamemberof:0.1-SNAPSHOT`
```

```scala
apackage.WhatEver.foo //works fine!
```

```scala
apackage.WhatEver.foo //error comes
```

error is

```
cmd2.sc:1: value foo is not a member of object apackage.WhatEver
val res2 = apackage.WhatEver.foo
``` 

See https://github.com/izhangzhihao/Jupyter-Scala-NotAMemberOf for example project & notebook

**Comment by alexarchambault** [comment]
Seems fine with the current master (and I guess most releases under the "almond" name should be fine too).
