### ISSUE TITLE
jupyter-scala with Actor

### ISSUE THREAD

**Issue by ssaumitra** [almond-sh/almond#160]
Are Scala actors not supported by jupyter-scala? When I tried the import,
```scala
import scala.actors.Actor
import scala.actors.Actor._
```
 I see the compilation error.
```
cmd0.sc:1: object actors is not a member of package scala
import scala.actors.Actor
             ^cmd0.sc:2: object actors is not a member of package scala
import scala.actors.Actor._
             ^
Compilation Failed
```

**Comment by jozi-k** [comment]
There is no such a thing like actors package in vanilla scala. This issue should be closed.

**Comment by konfer** [comment]
that is because actor is not a package of scala since the version 2.11, it is in te package akka,but i cannot import akka,so can anyone use the actor by this jupyter-scala?

**Comment by lichangjiang** [comment]
use akka actor like this:
> import $ivy.`com.typesafe.akka::akka-actor:2.5.13`  
> import akka.actor.Actor
