### ISSUE TITLE
Is it possible to use jupyter-scala with Spark 1.6.0 and Scala 2.10?

### ISSUE THREAD

**Issue by Myllyenko** [almond-sh/almond#162]
Hi!

Is it possible to use jupyter-scala with Spark 1.6.0 and Scala 2.10?

As jupyter-scala is published only for Scala 2.11, I've tried to rebuild it for Scala 2.10. The build has failed with non-existent `coursier-cli_2.10` dependency. Then I've rebuilt coursier-cli with Scala 2.10 and finally discovered that `coursier-cli_2.10` doesn't have the `coursier.cli.spark` package which is referenced by jupyter-scala.

**Comment by alexarchambault** [comment]
Not anymore for sure with the current master (and releases under the "almond" name), support for scala 2.10 was dropped from upstream dependencies of the kernel.
