### ISSUE TITLE
Compilation Failed

### ISSUE THREAD

**Issue by jmwoloso** [almond-sh/almond#164]
Hello,

attempting to use `ivy.load` results in the `Compilation Failed` and the traceback says:
 `cmd1.sc:1: not found: value load
val res1 = load.ivy("com.chuusai" %% "shapeless" % "2.20-RC6")`

Not sure what the problem is and any help would be appreciated. Thanks!

**Comment by anish749** [comment]
Try as described in README of this repo.
import $ivy.`org.apache.spark::spark-sql:2.1.0`

**Comment by alexarchambault** [comment]
Yeah, the syntax would be more
```
import $ivy.`com.chuusai::shapeless:2.3.3`
```
