### ISSUE TITLE
NoClassDefFoundError after kernel.sess.pop

### ISSUE THREAD

**Issue by Atry** [almond-sh/almond#165]
[SessPop.ipynb.zip](https://github.com/alexarchambault/jupyter-scala/files/1178981/SessPop.ipynb.zip)
![screen shot 2017-07-27 at 14 07 08](https://user-images.githubusercontent.com/601530/28656495-e92fa8cc-72d4-11e7-838a-ac8a1e25a1f8.png)

**Comment by alexarchambault** [comment]
It seems to work fine with the current master (using `repl.sess` instead of `kernel.sess`). Most releases under the "almond" name should be ok too.
