### ISSUE TITLE
Failure on vanilla dependency resolution

### ISSUE THREAD

**Issue by huitseeker** [almond-sh/almond#168]
On a notebook installed with the `./jupyter-scala` of 98bac7034f07e3e51d101846953aecbdb7a4bb5d (jupyter version 4.3.0), this single line:
```
import $ivy.`org.datavec:datavec-api:0.9.1`
```

gets 
```
ammonite.runtime.tools.DependencyThing$IvyResolutionException: failed to resolve dependencies:
  Dependency(org.datavec:datavec-api,0.9.1,compile,Set(),Attributes(,),false,true): not found: /home/huitseeker/.ivy2/local/org.datavec/datavec-api/0.9.1/ivys/ivy.xml, Name not found, Name not found
  ammonite.runtime.tools.DependencyThing.resolveArtifact(DependencyThing.scala:90)
  ammonite.interp.Interpreter.loadIvy(Interpreter.scala:658)
```

Full log : https://gist.github.com/huitseeker/c97bcd7821a2d293f2ea9e2ee292ff25

(expected behavior : correct resolution)

Yet this maven command-line shows the artifact is in maven-central (which is in the default resolvers) and accessible:
```
mvn -U org.apache.maven.plugins:maven-dependency-plugin:2.1:get \
    -DrepoUrl=http://download.java.net/maven/2/ \
    -Dartifact=org.datavec:datavec-api:0.9.1              
```

And the following `build.sbt` passes an `sbt update`:

```
name := "minimal-sbt"

version := "1.0"
libraryDependencies += "org.datavec" % "datavec-api" % "0.9.1"
```

Preparing the artifact through a local maven repo (with its jar) an setting the maven resolver manually:
```
{
  import Resolvers._

   val mavenResolver = 
   Resolver.File(
     "local",
     "/.m2/repository",
      MavenPattern,
      m2 = true
   )

  interp.resolvers() =  defaultResolvers :+ mavenResolver
}
```

Yields no positive change.

Also this is not an instance of https://github.com/lihaoyi/Ammonite/issues/664 or its incarnations, since this is a bona fide jar.

**Comment by alexarchambault** [comment]
That ought to be fixed in coursier. If created https://github.com/coursier/coursier/issues/647 for it.

**Comment by nightscape** [comment]
I created a PR to update coursier in ammonium: https://github.com/jupyter-scala/ammonium/pull/89
Will this fix this issue?
Is there a known workaround until then?

**Comment by alexarchambault** [comment]
@nightscape Yes, there is a workaround! You can just bump the version of coursier when jupyter-scala is fetched. Adding a `io.get-coursier:coursier-cli_2.11:1.0.1` around [here](https://github.com/jupyter-scala/jupyter-scala/blob/98bac7034f07e3e51d101846953aecbdb7a4bb5d/jupyter-scala#L42) should do (I've been actually doing something along those lines for some time…)

**Comment by alexarchambault** [comment]
It seems to be fine with the current master (and releases under the "almond" name should be ok too).
