### ISSUE TITLE
Wrapping scheme

### ISSUE THREAD

**Issue by aalexandrov** [almond-sh/almond#169]
In the standard Scala REPL, I can suffix a line with a `// show` comment in order to print out the wrapped object that is compiled. For example,

```scala
> val x = 42
> val y = Seq(x) // show
```

emits something along the following lines.

```scala
object $read$1 extends scala.AnyRef {
  object $iw extends scala.AnyRef {
    object $iw extends scala.AnyRef {
      val x = 42
    }
  }
}

object $read$2 extends scala.AnyRef {
  object $iw extends scala.AnyRef {
    import $read$1.$iw.$iw.x;
    object $iw extends scala.AnyRef {
      val y = Seq(x)
    }
  }
}
```

Is there a way to do something similar from an ammonium (or even better - Jupyter Scala) cell? Alternatively, can someone post the `cmdWrapper` code synthesized from the above example.

Many thanks in advance!

**Comment by alexarchambault** [comment]
I guess it's now more an [Ammonite](https://github.com/lihaoyi/Ammonite) question, since the rename as "almond". I'm not sure Ammonite allows that for now, maybe ask on its Gitter or open an issue in the Ammonite repo.
