### ISSUE TITLE
Error with JupyterSparkSession object 

### ISSUE THREAD

**Issue by bachsh** [almond-sh/almond#184]
I am getting an error while trying to work with JupyterSparkSession with master="local". It seems that the session is trying to connect to my gateway for some reason instead of trying to access localhost. Minimal replication code follows.
It's important for me to mention that initializing the session using the regular SparkSession object actually works well (I'm having trouble with using UDFs but other things including SparkML work fine).

Imports
```
import $exclude.`org.slf4j:slf4j-log4j12`, $ivy.`org.slf4j:slf4j-nop:1.7.21` // for cleaner logs
import $profile.`hadoop-2.6`
import $ivy.`org.apache.spark::spark-sql:2.1.0` // adjust spark version - spark >= 2.0
import $ivy.`org.jupyter-scala::spark:0.4.2` // for JupyterSparkSession (SparkSession aware of the jupyter-scala kernel)

import org.apache.spark._
import org.apache.spark.sql._
import jupyter.spark.session._
```

JupyterSparkSession Initialization
```
val sparkSession = JupyterSparkSession.builder() // important - call this rather than SparkSession.builder()
  .jupyter() // this method must be called straightaway after builder()
  .master("local") // change to "yarn-client" on YARN
  .appName("Demo App")
  .getOrCreate()
```

The next line generates the error
```
val df = sparkSession.read.format("csv")
    .option("header", "true")
    .load("data.csv")
```

Error message
```
org.apache.spark.SparkException: Job aborted due to stage failure: Task 0 in stage 0.0 failed 1 times, most recent failure: Lost task 0.0 in stage 0.0 (TID 0, localhost, executor driver): java.io.IOException: Failed to connect to /10.0.0.1:64622
```

**Comment by izhangzhihao** [comment]
Same issue here, it would be great if this will been fixed.

**Comment by alexarchambault** [comment]
That seems to be fine with the current master, see e.g. https://gist.github.com/alexarchambault/92b11406b7e586e7cb8032d2151af30b.
