### ISSUE TITLE
Need to split Scala Code in different Jupyter Scala Cells

### ISSUE THREAD

**Issue by animeshsrivastava24** [almond-sh/almond#195]
I have a scala file containing object & various methods defined in it. I want to split the code in various cells to show what each function is doing in it. But I can't.
For Jupyter- python we have  https://alexhagen.github.io/jdc/ to separate the classes or objects, is there anything for Jupyter-Scala, please help.
I tried for magic methods then I landed on the following link that says it's difficult to create magic methods : https://github.com/jupyter-scala/jupyter-scala/issues/44

**Comment by alexarchambault** [comment]
I guess that's now more an [Ammonite](http://ammonite.io/#Ammonite-REPL) issue than one for the kernel, that now mostly wraps Ammonite. (In the context of Ammonite, that would be equivalent of defining a class across several lines, evaluating each of them.) Ask on the gitter of Ammonite, or open an issue there, I guess.
