### ISSUE TITLE
not found: value $ivy on Windows 10

### ISSUE THREAD

**Issue by ZmeiGorynych** [almond-sh/almond#210]
Hi,

I've just downloaded jupyter-scala_2.11.6-0.2.0-SNAPSHOT.zip and installed jupyter-scala by running jupyter-scala.bat.

But then when I try to run the code from README to import Spark, I get a bunch of exceptions, see below.

Any idea how to fix it?

thanks a lot,
E.

![image](https://user-images.githubusercontent.com/22304254/44459646-4dc98d00-a602-11e8-940a-40e2a5ce3119.png)

**Comment by nightscape** [comment]
@ZmeiGorynych I don't know if this is still relevant, but you could try putting the
```scala
import org.apache.spark._
...
```
lines into a new cell.

**Comment by sbrunk** [comment]
There have been a lot of improvements in recent versions of jupyter-scala (now almond).

* The [installation instructions](https://almond.sh/docs/quick-start-install) now include steps for a windows installation.
* [Spark integration](https://almond.sh/docs/usage-spark) is also documented.

If it's still relevant, could you check if you still run into issues using the current version?

**Comment by ZmeiGorynych** [comment]
@sbrunk Thanks a lot for the update! I'm not currently looking at this, but will keep it in mind once I come back to it.

**Comment by sbrunk** [comment]
Ok closing then. Feel free to reopen in case you come back to it and still run into this issue.
