### ISSUE TITLE
Handle shutdown messages

### ISSUE THREAD

**Issue by jameskoch2** [almond-sh/almond#220]
Here's how IPython handles it - https://github.com/ipython/ipykernel/blob/f2e9895a6217c53c3912a0fdeb306a8316fd62fd/ipykernel/kernelbase.py#L526

Notably the v5.3 spec states "The request can be sent on either the control or shell channels.".

I may attempt this myself, but I'm new to cats effects and struggling a bit to sort it all out.

**Comment by alexarchambault** [comment]
Fixed by https://github.com/almond-sh/almond/pull/222 (included in `0.1.8`).
