### ISSUE TITLE
Implement auto-complete of `Symbols with Backquotes`

### ISSUE THREAD

**Issue by jameskoch2** [almond-sh/almond#221]
FWIW, none of the other Scala kernels do this properly.

**Comment by jameskoch2** [comment]
Looks like current implementation is inherited from Scala itself, so I filed https://github.com/scala/bug/issues/11140

**Comment by jameskoch** [comment]
This is fixed as of ac8c4248fe1a38961a49697ee1abe87c38c2603d.

It's not perfect, but it's a lot better than nothing.

Given ```class Foo(val `bar baz`: Int)``` you can complete these:
1. `instance.<tab>`
2. `instance.b<tab>`

But not ```instance.`<tab>```.

**Comment by alexarchambault** [comment]
@jameskoch2 So we can close then? Remaining issues can always be reported directly to Ammonite I guess.

**Comment by jameskoch** [comment]
Agreed. Thanks!
