### ISSUE TITLE
Trying to get ammonite-spark to work with existing spark classpath

### ISSUE THREAD

**Issue by erikerlandson** [almond-sh/almond#227]
I have a container image with spark jars pre-installed in directory "/opt/spark/jars"
I can do the trick to add the classpath, and load `ammonite-spark`. I am running ammonite via notebook as `almond-0.1.7`.

However, when I try doing it this way it fails in the following way:

![image](https://user-images.githubusercontent.com/259898/45851928-1aa61680-bcf2-11e8-80cd-4e7fb3b2a3fb.png)

**Comment by erikerlandson** [comment]
for comparison, doing it using all ivy magic, like 
```scala
import $ivy.`org.apache.spark::spark-sql:2.3.1`
import $ivy.`sh.almond::ammonite-spark:0.1.1`
```
seems to work

**Comment by alexarchambault** [comment]
@erikerlandson I think you have to add each jar under `/opt/spark/jars` via `interp.load.cp`, rather than their directory.

**Comment by erikerlandson** [comment]
Aha. That's a lot of jars, but I guess I can try doing it in a loop. I wonder how hard it would be to have it understand directories.

**Comment by alexarchambault** [comment]
@erikerlandson `interp.load.cp` can be passed a `Seq[ammonite.ops.Path]`, to load all files at once.
