### ISSUE TITLE
Write a contributor guide

### ISSUE THREAD

**Issue by rgbkrk** [almond-sh/almond#232]
I'd love to point more folks to almond, whether they be writers, developers, designers, or users. One thing that really helps cultivate community support is something as simple as a `CONTRIBUTING.md`. It can start with, at the very basic level:

* a welcome statement
* how to build the project
* how to contribute fixes (any practices you'd like adhered to)

Examples

* https://github.com/nodejs/node/blob/master/CONTRIBUTING.md
* https://github.com/nteract/nteract/blob/master/CONTRIBUTING.md
* https://www.gatsbyjs.org/docs/how-to-contribute/

**Comment by alexarchambault** [comment]
Agreed... I'm going to look into that.
