### ISSUE TITLE
Adding almond to Docusaurus users page

### ISSUE THREAD

**Issue by andrewShillito** [almond-sh/almond#259]
Docusaurus would like to add your logo to their [users page](https://docusaurus.io/en/users).  If that is something you are interested in could you direct me to the logo you would like to use?  The image would need to be no larger than 512x512 and .svg if possible.

More information about this topic [here](https://github.com/facebook/Docusaurus/issues/1080).

Thank you

**Comment by alexarchambault** [comment]
Sorry this slipped my attention at the time… Discussing this here: https://github.com/almond-sh/almond/issues/362.

**Comment by Hongarc** [comment]
Oh I don't see this issue before create new issue

**Comment by andrewShillito** [comment]
Saw the comments in #362.  Thanks @alexarchambault.  If you all design a log in the future I'm sure @Hongarc or myself will be happy to help in adding it to the Docusaurus page.  Until then best wishes.
