### ISSUE TITLE
How to install Scala kernel into `/usr/local/share/jupyter/kernels/`?

### ISSUE THREAD

**Issue by dclong** [almond-sh/almond#261]
By default, the generated launch installs the Scala kernel to the current user's home directory. For example, if installed using `root`, it is under `/root/.local/share/jupyter/kernels/scala`. Howe to make the launcher to install the Scala kernel into `/usr/local/share/jupyter/kernels/`?

**Comment by sbrunk** [comment]
Have you tried using the `--global` flag as [described in the install docs](http://almond-sh.github.io/almond/stable/docs/install-options.html#global)?

```bash
./almond --install --global
```
 should install the kernel under `/usr/local/share/jupyter/kernels/`.

**Comment by dclong** [comment]
@sbrunk Thank you so much for your quick response! It works great. Sorry that I referred to the quick installation guide instead. Should have check the full doc before asking here.
