### ISSUE TITLE
":type 1" returns an error

### ISSUE THREAD

**Issue by pmav99** [almond-sh/almond#267]
On the REPL you can check the type of an instance by using `type`. E.g.:
``` scala
:type 1
```
On Jupyter this throws an exception:
``` scala
(console):1:1 expected end-of-input
:type 1
^
```

**Comment by alexarchambault** [comment]
almond relies on the [Ammonite](http://ammonite.io/) scala shell. Look for `typeOf` in its [documentation](http://ammonite.io/)., it allows to get the type of expressions, like
```
@ typeOf(1).toString
res1: String = "Int"
```
