### ISSUE TITLE
Suppress printing of Display values

### ISSUE THREAD

**Issue by lourkeur** [almond-sh/almond#287]
When using `almond.api.Display` objects to create rich output, the string representation appears at the end of the cell, which is unnecessary. (as discussed at Scala Spree Lausanne)

We discussed trying to suppress that output. This can easily be done by making the kernel run `implicitly[JupyterApi].register[Display]{ _ => Map.empty }`, but I don't really see where to shoehorn it into the kernel starting process. Any pointers?

Before (undesirable):
![capture d ecran de 2018-12-15 15-28-12](https://user-images.githubusercontent.com/15657735/50044108-1aae7c00-007f-11e9-94f9-4f6cfad7666d.png)

After (better):
![capture d ecran de 2018-12-15 15-36-27](https://user-images.githubusercontent.com/15657735/50044167-f1dab680-007f-11e9-99fa-af34e133ec55.png)

**Comment by jameskoch** [comment]
Narrowly addressing your work-around idea, you can shoe-horn in kernel-initialization code using this - http://almond-sh.github.io/almond/stable/docs/install-options.html#scala-related

**Comment by jameskoch** [comment]
Very closely related to #256.

**Comment by sbrunk** [comment]
With the new [display API](https://almond.sh/docs/api-jupyter.html#display),  display value string representation aren't printend anymore.

As of #450, we can also suppress all non-explicit output by setting `kernel.silent(true)`
