### ISSUE TITLE
Install-error, jvm-repr not found, cannot install 0.2.1

### ISSUE THREAD

**Issue by ThijsBroersen** [almond-sh/almond#294]
Error:
  com.github.jupyter:jvm-repr:0.3.1
    No fallback URL found
    not found: /home/jovyan/.ivy2/local/com.github.jupyter/jvm-repr/0.3.1/ivys/ivy.xml
    not found: https://repo1.maven.org/maven2/com/github/jupyter/jvm-repr/0.3.1/jvm-repr-0.3.1.pom

I think this repository is missing: http://maven.imagej.net/content/repositories/public/ 
See also: https://mvnrepository.com/artifact/com.github.jupyter/jvm-repr/0.3.1

**Comment by sbrunk** [comment]
Have you added `-r jitpack` in `coursier-bootstrap` as described in http://almond-sh.github.io/almond/0.2.0/docs/quick-start-install?

See also #283

**Comment by ThijsBroersen** [comment]
> Did you add `-r jitpack` in `coursier-bootstrap` as described in http://almond-sh.github.io/almond/0.2.0/docs/quick-start-install?
> 
> See also #283

Yep, you are right! My bad! Overlooked this change. I will close this issue.
