### ISSUE TITLE
How to run graphx with jupyter-scala?

### ISSUE THREAD

**Issue by bydali** [almond-sh/almond#305]
i installed jupyter-scala from [https://github.com/almond-sh/almond](url),but there still has some problems in running graphx?how to import these missing packages?
![default](https://user-images.githubusercontent.com/12482918/51153305-941dd200-18aa-11e9-9524-02adea667b63.PNG)

**Comment by sbrunk** [comment]
You have to import the *almond-spark* module first as well as Spark itself, like so:

```scala
import $ivy.`org.apache.spark::spark-sql:2.4.0`
import $ivy.`org.apache.spark::spark-graphx:2.4.0`
import $ivy.`sh.almond::almond-spark:0.3.0`
```

Then, create a Spark session and a context:
```scala
import org.apache.spark.sql._
import org.apache.spark.graphx._
import org.apache.spark.rdd.RDD

val spark = {
  NotebookSparkSession.builder()
    .master("local[*]")
    .getOrCreate()
}
def sc = spark.sparkContext
```

Now you should be able to create graphs and run computations, i.e. from the [GraphX Programming Guide](https://spark.apache.org/docs/latest/graphx-programming-guide.html#getting-started):

```scala
// Create an RDD for the vertices
val users: RDD[(VertexId, (String, String))] =
  sc.parallelize(Array((3L, ("rxin", "student")), (7L, ("jgonzal", "postdoc")),
                       (5L, ("franklin", "prof")), (2L, ("istoica", "prof"))))
// Create an RDD for edges
val relationships: RDD[Edge[String]] =
  sc.parallelize(Array(Edge(3L, 7L, "collab"),    Edge(5L, 3L, "advisor"),
                       Edge(2L, 5L, "colleague"), Edge(5L, 7L, "pi")))
// Define a default user in case there are relationship with missing user
val defaultUser = ("John Doe", "Missing")
// Build the initial Graph
val graph = Graph(users, relationships, defaultUser)

// Count all users which are postdocs
graph.vertices.filter { case (id, (name, pos)) => pos == "postdoc" }.count
// Count all the edges where src > dst
graph.edges.filter(e => e.srcId > e.dstId).count
```

We'll add some documentation on Spark with almond soon.

**Comment by bydali** [comment]
thank you , i have tried using the above snippet , that works ,

**Comment by sbrunk** [comment]
Great! Closing then.

By the way, we now have Spark usage covered in the [docs (dev version)](https://almond.sh/docs/next/usage-spark).
