### ISSUE TITLE
Error at installation: sh.almond:scala-kernel_: No fallback URL found

### ISSUE THREAD

**Issue by marek-grzymala** [almond-sh/almond#314]
Trying to install on Ubuntu 18, running the command:

`sudo ./coursier bootstrap -r jitpack -i user -I user:sh.almond:scala-kernel-api_$SCALA_VERSION:$ALMOND_VERSION sh.almond:scala-kernel_$SCALA_VERSION:$ALMOND_VERSION -o almond`

I get:

`Error:
  sh.almond:scala-kernel_:
    No fallback URL found
    not found: /home/sparkuser/.ivy2/local/sh.almond/scala-kernel_/ivys/ivy.xml
    not found: https://repo1.maven.org/maven2/sh/almond/scala-kernel_//scala-kernel_-.pom
    not found: https://jitpack.io/sh/almond/scala-kernel_//scala-kernel_-.pom`

Tried multiple times and I am not behind any proxy (all other packages install just fine)

**Comment by sbrunk** [comment]
Looks like the environment variables are set or are not used properly.
Did you set them before running coursier bootstrap as described in the install docs?
```bash
SCALA_VERSION=2.12.8 ALMOND_VERSION=0.2.2
```

What's the output of `echo $ALMOND_VERSION` ?

**Comment by sbrunk** [comment]
Also using `sudo` is usually not required for running `coursier bootstrap`

**Comment by frgomes** [comment]
@marek-grzymala : FYI, I have a shell script which automates it all:
https://github.com/frgomes/bash-scripts/blob/master/user-install/install-jupyter.sh

**Comment by marek-grzymala** [comment]
never mind, after a restart the install went through just fine, thanks everyone anyway
