### ISSUE TITLE
Failure to update to almond 0.3.0

### ISSUE THREAD

**Issue by frgomes** [almond-sh/almond#320]
I have a shell script [here](https://github.com/frgomes/bash-scripts/blob/master/user-install/install-jupyter.sh) which /automagically/ installs pip, coursier, jupyter and almond.
The script works just fine in its current form, installing almond 0.2.2.

I've changed almond version to 0.3.0 locally, on my working folder (still not pushed onto git) and I've got the following error:

```bash
+ coursier bootstrap -r jitpack -i user -I user:sh.almond:scala-kernel-api_2.12.8:0.3.0 sh.almond:scala-kernel_2.12.8:0.3.0 -f -o /home/rgomes/bin/almond

Error:
  sh.almond:scala-kernel_2.12.8:0.3.0
    No fallback URL found
    not found: /home/rgomes/.ivy2/local/sh.almond/scala-kernel_2.12.8/0.3.0/ivys/ivy.xml
    not found: https://repo1.maven.org/maven2/sh/almond/scala-kernel_2.12.8/0.3.0/scala-kernel_2.12.8-0.3.0.pom
    not found: https://jitpack.io/sh/almond/scala-kernel_2.12.8/0.3.0/scala-kernel_2.12.8-0.3.0.pom
```

Ideas?

**Comment by alexarchambault** [comment]
It seems to work now for me (your command runs fine on my machine).

When did you try to run that command? The tag is pushed in the git repo before the release is actually available on Sonatype releases or Maven Central. (The git tag actually triggers the CI jobs that publish the artifacts.)

OTOH, the version on the website is updated once things are available on Sonatype releases and sync-ed to Maven Central.

**Comment by frgomes** [comment]
@alexarchambault : 
I've tried again. My script is working now with almond 0.3.0.
I've updated my shell script and pushed on to the repository.
If you find it helpful for users, please feel free to copy it, etc.
Thanks a lot for your great work on almond! :-)
