### ISSUE TITLE
Adding new imports issue

### ISSUE THREAD

**Issue by sbushmanov** [almond-sh/almond#333]
I am trying to add import `joda-time` from https://mvnrepository.com/artifact/joda-time/joda-time/2.10.1

```
<!-- https://mvnrepository.com/artifact/joda-time/joda-time -->
<dependency org="joda-time" name="joda-time" rev="2.10.1"/>
```

The code goes like this:
```
import $ivy.`org.joda-time::joda-time:2.10-1`
```

However I'm getting errors:

```
Downloading https://repo1.maven.org/maven2/org/joda-time/joda-time_2.11/2.10-1/joda-time_2.11-2.10-1.pom
Downloading https://repo1.maven.org/maven2/org/joda-time/joda-time_2.11/2.10-1/joda-time_2.11-2.10-1.pom.sha1
Failed to resolve ivy dependencies:
  org.joda-time:joda-time_2.11:2.10-1 
    not found: /home/sergey/.ivy2/local/org.joda-time/joda-time_2.11/2.10-1/ivys/ivy.xml
    not found: https://repo1.maven.org/maven2/org/joda-time/joda-time_2.11/2.10-1/joda-time_2.11-2.10-1.pom
Failed to resolve ivy dependencies:
  org.joda-time:joda-time_2.11:2.10-1 
    not found: /home/sergey/.ivy2/local/org.joda-time/joda-time_2.11/2.10-1/ivys/ivy.xml
    not found: https://repo1.maven.org/maven2/org/joda-time/joda-time_2.11/2.10-1/joda-time_2.11-2.10-1.pom

```

Can somebody point me to the right direction what am I doing wrong and what fildes in https://mvnrepository.com/artifact/joda-time/joda-time/2.10.1 correspong to what fields in `ivy` import statement?

**Comment by shadaj** [comment]
@sbushmanov looks like you have an extra colon between `org.joda-time` and `joda-time`. So the correct code would be

```
import $ivy.`org.joda-time:joda-time:2.10-1`
```

The `::` indicates that the library is a Scala library and so the Scala version is appended to the name (hence the generated `joda-time_2.11` instead of just `joda-time`). Since `joda-time` is a regular Java library, just a single colon should be used.

**Comment by sbushmanov** [comment]
@shadaj Thank you for the explanation!
