### ISSUE TITLE
Switch build over to mill

### ISSUE THREAD

**Issue by alexarchambault** [almond-sh/almond#356]
I'm more and more considering switching the build from sbt to [mill](http://www.lihaoyi.com/mill/). Even though mill is a young project, it seems to work rather well already (it's used by [Ammonite](https://github.com/lihaoyi/Ammonite/) in particular).

This would allow to scrap a number of more or less flaky scripts here, and replace them with proper tasks within mill:
- [website-related scripts](https://github.com/almond-sh/almond/blob/a4cffe01f5a45b0c7c3e38a13ceac834b11c6615/scripts/site.sc),
- [examples-related](https://github.com/almond-sh/almond/blob/a4cffe01f5a45b0c7c3e38a13ceac834b11c6615/scripts/setup-and-validate-examples.sh) [scripts](https://github.com/almond-sh/almond/blob/a4cffe01f5a45b0c7c3e38a13ceac834b11c6615/scripts/validate-examples.sh),
- [generate launcher script](https://github.com/almond-sh/almond/blob/a4cffe01f5a45b0c7c3e38a13ceac834b11c6615/scripts/generate-launcher.sh).

This would also allow to have the current [run from sources](https://almond.sh/docs/0.3.1/dev-from-sources) mechanism rely on an actual kernel launcher with class-loader isolation, rather than an sbt-pack based distribution.

**Comment by sequencer** [comment]
Any updates on porting to mill?
