### ISSUE TITLE
Featuring almond in Docusaurus

### ISSUE THREAD

**Issue by Hongarc** [almond-sh/almond#362]
Hello, we would like to feature your project to the Docusaurus users page.

Are you with me on this? Also, can you provide your logo?

More info about this [here](https://github.com/facebook/Docusaurus/issues/1080)

**Comment by alexarchambault** [comment]
@Hongarc I guess I'm ok being featured on the docusaurus users page. But the thing is, we don't have a logo :|

**Comment by Hongarc** [comment]
Can you try to create a logo?

**Comment by sbrunk** [comment]
@andrewShillito @Hongarc in case your still interested in this, we have a logo now, see the README.

**Comment by andrewShillito** [comment]
@sbrunk @Hongarc Cool thanks for letting me know.  I am traveling with no computer right now so if hongarc or whoever wants to submit the change to docusaurus that’s fine with me.  If it isn’t done by the time I get back I will make the PR to docusaurus.

**Comment by Hongarc** [comment]
Check it [here](https://docusaurus.io/en/users)
![image](https://user-images.githubusercontent.com/19208123/61177967-6670d600-a60c-11e9-9da4-4fa2650f80c9.png)
