### ISSUE TITLE
Import the almond-spark dependency

### ISSUE THREAD

**Issue by muideenlawal** [almond-sh/almond#374]
**When I tried;**

`import $ivy.org.apache.spark::spark-sql:2.4.0`
`import $ivy.sh.almond::almond-spark:@VERSION@`

**I got the following errors:**

`Failed to resolve ivy dependencies:Error downloading sh.almond:almond-spark_2.12:@VERSION@
  not found: /Users/.ivy2/local/sh.almond/almond-spark_2.12/@VERSION@/ivys/ivy.xml
  not found: https://repo1.maven.org/maven2/sh/almond/almond-spark_2.12/@VERSION@/almond-spark_2.12-@VERSION@.pom`

I have tried several methods and even reinstall almond but the errors won't go away.

**Comment by sbrunk** [comment]
@VERSION@ is a template that is replaced with the current almond version during doc generation.

If you look at the [spark docs](https://almond.sh/docs/usage-spark) through the website, you should see a real version you can use (if you've installed the latest kernel version):

```scala
import $ivy.`org.apache.spark::spark-sql:2.4.0` // Or use any other 2.x version here
import $ivy.`sh.almond::almond-spark:0.5.0`
```

**Comment by muideenlawal** [comment]
Thank you. This works! It was an oversight on my part.
