### ISSUE TITLE
Importing breeze

### ISSUE THREAD

**Issue by Quafadas** [almond-sh/almond#393]
I'm trying this project for the first time - I've successfully pulled down the image from docker. 

I was curious about trying breeze. Below is what the docs and prior breeze issue appear to suggest. Breeze does appear to download successfully. I've since tried restarting the kernel etc, to no avail. Here's my notebook / cell... 

```
import $ivy.`org.scalanlp::breeze:0.13.2`
import $ivy.`org.scalanlp::breeze-natives:0.13.2`
val y = DenseVector(1,2,3,4)
```
I get a compile  error... 

`cmd3.sc:1: not found: value DenseVector
val y = DenseVector(1,2,3,4)
        ^Compilation Failed`

Can anyone see a problem here?  Would this be expected to work?

**Comment by sbrunk** [comment]
You still need to import the package in addition to importing the library. The following works fine for me:

```scala
import $ivy.`org.scalanlp::breeze:0.13.2`
import $ivy.`org.scalanlp::breeze-natives:0.13.2`

import breeze.linalg._
val y = DenseVector(1,2,3,4)
```

**Comment by Quafadas** [comment]
Thankyou - apologies - in hindsight, that's a very obvious step...
