### ISSUE TITLE
Update docs for Almond scala-kernel_2.13.0 ?

### ISSUE THREAD

**Issue by mslinn** [almond-sh/almond#417]
The Almond installation docs discuss Almond version 0.4.0, but I see 0.6.0 and 0.7.0 exist for Scala 2.13.0. [My Almond build script](https://gist.github.com/mslinn/b5ac2ce34146440b517747d2a91d828e#file-buildalmond) works for Scala 2.13.0 and Almond 0.7.0. Is there any reason this should not be mentioned in the installation docs?

```bash
$ buildAlmond -s 2.13.0 -a 0.7.0 -f
 ... lots of output
Available kernels:
  python3         /home/mslinn/.local/share/jupyter/kernels/python3
  scala           /home/mslinn/.local/share/jupyter/kernels/scala
  scala2.11.12    /home/mslinn/.local/share/jupyter/kernels/scala2.11.12
  scala2.12.8     /home/mslinn/.local/share/jupyter/kernels/scala2.12.8
  scala2.13.0     /home/mslinn/.local/share/jupyter/kernels/scala2.13.0
  python2         /usr/local/share/jupyter/kernels/python2
```

**Comment by slel** [comment]
The docs now have something about versions 0.6.0, 0.7.0, 0.8.0:

- https://almond.sh/docs/install-versions

but with Almond 0.9.0 now out, that documentation page
should again be updated.

The release notes at

- https://github.com/almond-sh/almond/releases

say 0.9.0 removed support for Scala 2.12.6 and 2.12.7.

See pull request: https://github.com/almond-sh/almond/pull/473
