### ISSUE TITLE
Combination of Scala 2.11.12 and almond 0.7.0 fails to download

### ISSUE THREAD

**Issue by queirozfcom** [almond-sh/almond#424]
Off the [official tutorial](https://almond.sh/docs/quick-start-install): 

 **download coursier**
```
$ curl -Lo coursier https://git.io/coursier-cli
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:--  0:00:01 --:--:--     0
100   135  100   135    0     0     53      0  0:00:02  0:00:02 --:--:--   548
100 20720  100 20720    0     0   6333      0  0:00:03  0:00:03 --:--:--  266k
```

**install almond**

```
$ ./coursier bootstrap \
>     -r jitpack \
>     -i user -I user:sh.almond:scala-kernel-api_2.11.12:0.7.0 \
>     sh.almond:scala-kernel_2.11.12:0.7.0 \
>     -o almond
Resolution error: Error downloading sh.almond:scala-kernel_2.11.12:0.7.0
  not found: /home/felipe/.ivy2/local/sh.almond/scala-kernel_2.11.12/0.7.0/ivys/ivy.xml
  not found: https://repo1.maven.org/maven2/sh/almond/scala-kernel_2.11.12/0.7.0/scala-kernel_2.11.12-0.7.0.pom
  not found: https://jitpack.io/sh/almond/scala-kernel_2.11.12/0.7.0/scala-kernel_2.11.12-0.7.0.pom
```

**Comment by queirozfcom** [comment]
P.S.: I can install 2.11.12 with other almond versions and I can install other scala versions with almond 0.7.0 so I think the problem is specifically with this scala-almond combination

**Comment by mardukbp** [comment]
In the Releases page you will see that almond 0.7.0 uses Ammonite 1.6.9, which only supports Scala 2.12 and 2.13. Therefore, you should use almond 0.6.0 with Scala 2.11.x.

**Comment by queirozfcom** [comment]
@mardukbp they updated the docs in the 0.8.0 release. I'm closing this.

**Comment by sbrunk** [comment]
Thanks @mardukbp, it's indeed due to Ammonite having dropped support for 2.11

Wer're having a little hickup in the publishing process right now, so the website is not updated yet and 0.8.0 artifacts aren't on maven central. Should all be sorted out soon.
