### ISSUE TITLE
Docker images are not being published

### ISSUE THREAD

**Issue by hohonuuli** [almond-sh/almond#444]
It looks like there's a script, [scripts/update-docker-images.sh](https://github.com/almond-sh/almond/blob/master/scripts/update-docker-images.sh) in [.travis.yml](https://github.com/almond-sh/almond/blob/master/.travis.yml) that's supposed to build and push a new image to dockerhub when a release is tagged. The current almond.sh release is __0.8.2__, but the last tag on dockerhub is __0.6.0__. 

Because of this the instructions at <https://almond.sh/docs/try-docker> don't work.

**Comment by hohonuuli** [comment]
Also, thanks for your work @alexarchambault!

**Comment by sbrunk** [comment]
Thanks @hohonuuli  for catching this. the update-docker-images script is indeed failing in CI since 0.6.0

**Comment by sbrunk** [comment]
Seems like the docker daemon on travis ignores the ONBUILD directive causing it to fail when trying to copy a non-existing `ivy-local` directory.
Works fine locally with Docker 19.03.1

https://github.com/almond-sh/almond/blob/a748d44d2de2475abe38d0a52b963402fd5f2ca0/Dockerfile#L29-L32

**Comment by sbrunk** [comment]
@hohonuuli The Docker builds are fixed now and @alexarchambault has re-published images for the latest release:
https://hub.docker.com/r/almondsh/almond/tags

**Comment by hohonuuli** [comment]
@sbrunk Thanks for fixing that. Cheers.
