### ISSUE TITLE
Allow silencing of REPL output from Jupyter API

### ISSUE THREAD

**Issue by trepidacious** [almond-sh/almond#449]
In some of the notebooks I've been working on, all relevant results are presented as html tables, plotly graphs, etc. This means that the REPL output (variable definitions, imports etc.) is not really adding any extra information, and tends to get in the way of the data. Reducing the `defaultHeight` in `pprinter` helps, but since there are still quite a lot of individual lines of code it still leaves a lot of unwanted output.

Looking through the code, there is a parameter `silent` in `ammonite.interp.Interpreter.processLine`, which is called from `almond.Execute`. Setting this to true seems to have the desired effect of removing REPL output, while preserving `Display` and `println` output. I've had a quick look in the ammonite code and it seems to do what you would expect :)

I'll put together a pull request to add a `silent` property to `kernel`, which can be used as follows:

<img width="659" alt="Screen Shot 2019-10-14 at 10 56 07" src="https://user-images.githubusercontent.com/172154/66743192-481bb000-ee71-11e9-8209-f1233885c63f.png">

I'm new to the Almond code (I'm really enjoying using it, thanks!), so I'm not sure that this is the right place to put the setting, or that the implementation is correct, but it does demonstrate how the feature would work :)

**Comment by sbrunk** [comment]
Implemented in #450
