### ISSUE TITLE
Help request: Convert jupyter.api.Publish usage to Almond

### ISSUE THREAD

**Issue by hohonuuli** [almond-sh/almond#469]
This is a request for assistance. I'm working on updating [EvilPlot](https://github.com/cibotech/evilplot) to work with Scala 2.13 and Almond.sh. There's some code used to render images in notebooks running the old jupyter-scala kernel and I'd like to update it to work with Almond. The jupyter-scala code in question is below, advice on converting it to work with Almond is much appreciated. Basically, here's the code I need updated to Almond:

```scala
 def show(implicit publish: jupyter.api.Publish): Unit =
      publish.png(drawable.asBufferedImage)
```

Full code is below:

### JupyterScala.scala

```scala
package com.cibo.evilplot

import com.cibo.evilplot.plot.Plot
import com.cibo.evilplot.geometry.Drawable
import com.cibo.evilplot.plot.aesthetics.Theme

/** implicits and methods for jupyter-scala */
object JupyterScala {

  /** enhanced methods on Drawable objects for jupyter-scala */
  implicit class JupyterScalaDrawableMethods(drawable: Drawable) {

    /** display this Drawable object directly in the jupyter-scala output cell */
    def show(implicit publish: jupyter.api.Publish): Unit =
      publish.png(drawable.asBufferedImage)
  }

  /** enhanced methods on Plot objects for jupyter-scala */
  implicit class JupyterScalaPlotMethods(plot: Plot) {

    /** display this Plot object directly in the jupyter-scala output cell */
    def show(implicit publish: jupyter.api.Publish, theme: Theme): Unit =
      publish.png(plot.render()(theme).asBufferedImage)
  }
}

```

**Comment by sbrunk** [comment]
@hohonuuli I created an [example notebook for EvilPlot]( https://github.com/almond-sh/examples/blob/master/notebooks/visualization/evilplot.ipynb) some time ago.
I didn't know that EvilPlot has support for the old jupyter-scala API until now, so it contains this helper function:

```scala
def showPlot(plot: com.cibo.evilplot.geometry.Drawable) =
  Image.fromRenderedImage(plot.asBufferedImage, format=Image.PNG)
```

The `Image` class is part of the [Jupyter API](https://almond.sh/docs/api-jupyter.html#high-level-api), so if you add that as provided dependency as described in https://almond.sh/docs/api-access-instances it should be just what you need.

**Comment by hohonuuli** [comment]
@sbrunk Thanks for the pointer! I believe that is exactly what I needed.
