### ISSUE TITLE
NullPointerException in ReplApiImpl.printSpecial

### ISSUE THREAD

**Issue by andrelfpinto** [almond-sh/almond#475]
Hello,

First, thank you for the amazing project!

I am trying to use the [scala-scraper](https://github.com/ruippeixotog/scala-scraper) project in JupyterLab. When I have a notebook with:

```
import $ivy.`net.ruippeixotog::scala-scraper:2.2.0`

import net.ruippeixotog.scalascraper.browser.JsoupBrowser

val browser = JsoupBrowser()
val doc = browser.get("https://google.com")
```

I get:

```
java.lang.NullPointerException
  almond.ReplApiImpl.printSpecial(ReplApiImpl.scala:50)
  almond.JupyterApiImpl.printOnChange(JupyterApiImpl.scala:35)
  almond.api.FullJupyterApi$Internal$.printOnChange(FullJupyterApi.scala:27)
```

This is line 50 in [ReplApiImpl.scala](https://github.com/almond-sh/almond/blob/085b4a183acba6a4c07a39e0b9214138a44e2405/modules/scala/scala-interpreter/src/main/scala/almond/ReplApiImpl.scala#L50):

```
        Displayers.registration().find(classTagT.runtimeClass)
```

The problem is that I don't even understand enough to identify if it is a problem in Almond or in scala-scraper.

I am using:

```
Almond 0.9.0
Ammonite 1.7.4
Scala library version 2.12.10 -- Copyright 2002-2019, LAMP/EPFL and Lightbend, Inc.
Java 1.8.0_171
```

Thank you.

**Comment by alexarchambault** [comment]
Not sure, but `classTagT` is possibly `null`:
```scala
def classTag[T](t: => T)(implicit c: reflect.ClassTag[T]) = c
classTag(browser.get("https://google.com"))
```
fails with
```
cmd2.sc:1: No ClassTag available for cmd2.this.cmd0.browser.DocumentType
val res2 = classTag(browser.get("https://google.com"))
                   ^

Compilation Failed
```

Not sure under which conditions this `ClassTag` can be `null`, but the code around https://github.com/almond-sh/almond/blob/085b4a183acba6a4c07a39e0b9214138a44e2405/modules/scala/scala-interpreter/src/main/scala/almond/ReplApiImpl.scala#L50 should definitely be fine with a null `classTagT` (`jvmReprDisplayer` should be set to `defaultDisplayer` then).

**Comment by andrelfpinto** [comment]
Maybe something like:

```Option[ClassTag[T]](classTagT).map(
  ct => Displayers.registration().find(ct.runtimeClass)).getOrElse(defaultDisplayer)
```

would solve the problem?

**Comment by alexarchambault** [comment]
@andrelfpinto Yes, or even just
```scala
if (classTagT == null) defaultDisplayer
else Displayers.registration().find(classTagT.runtimeClass)
```

**Comment by alexarchambault** [comment]
Fixed by https://github.com/almond-sh/almond/pull/477.
