### ISSUE TITLE
First class support for offline installations?

### ISSUE THREAD

**Issue by kwlzn** [almond-sh/almond#476]
at Twitter, we'd like to use Almond in our Jupyter Notebook offering that operates on server grade hardware behind a tightly controlled firewall with access to only e.g. an internal Artifactory repo/mirror. however, the way Almond is currently designed/documented seems to assume public internet access by default.

even with `--extra-repository` as fallback, an install of Almond built in an environment with internet access (e.g. in Docker) cannot be stashed and installed on an offline host (e.g. in a datacenter without internet access) with a functional kernel. this manifests in the notebook server logs as e.g.:

```
[I 07:38:00.273 NotebookApp] Kernel started: b279ce9d-2d6a-4f79-8da0-3de1b65cb2d9
Error while downloading https://repo1.maven.org/maven2/com/fasterxml/jackson/core/jackson-databind/2.9.6/jackson-databind-2.9.6.jar: Ongoing concurrent download for https://repo1.maven.org/maven2/com/fasterxml/jackson/core/jackson-databind/2.9.6/jackson-databind-2.9.6.jar, ignoring it
[I 07:38:03.271 NotebookApp] KernelRestarter: restarting kernel (1/5), new random ports
Error while downloading https://repo1.maven.org/maven2/com/fasterxml/jackson/core/jackson-core/2.9.6/jackson-core-2.9.6.jar: Ongoing concurrent download for https://repo1.maven.org/maven2/com/fasterxml/jackson/core/jackson-core/2.9.6/jackson-core-2.9.6.jar, ignoring it
[I 07:38:06.283 NotebookApp] KernelRestarter: restarting kernel (2/5), new random ports
Error while downloading https://repo1.maven.org/maven2/com/fasterxml/jackson/core/jackson-databind/2.9.6/jackson-databind-2.9.6.jar: Ongoing concurrent download for https://repo1.maven.org/maven2/com/fasterxml/jackson/core/jackson-databind/2.9.6/jackson-databind-2.9.6.jar, ignoring it
Error while downloading https://repo1.maven.org/maven2/co/fs2/fs2-core_2.12/2.0.0/fs2-core_2.12-2.0.0.jar: Ongoing concurrent download for https://repo1.maven.org/maven2/co/fs2/fs2-core_2.12/2.0.0/fs2-core_2.12-2.0.0.jar, ignoring it[I 07:38:09.296 NotebookApp] KernelRestarter: restarting kernel (3/5), new random ports
Error while downloading https://repo1.maven.org/maven2/com/fasterxml/jackson/core/jackson-databind/2.9.6/jackson-databind-2.9.6.jar: Ongoing concurrent download for https://repo1.maven.org/maven2/com/fasterxml/jackson/core/jackson-databind/2.9.6/jackson-databind-2.9.6.jar, ignoring it
Error while downloading https://repo1.maven.org/maven2/com/fasterxml/jackson/core/jackson-annotations/2.9.0/jackson-annotations-2.9.0.jar: Ongoing concurrent download for https://repo1.maven.org/maven2/com/fasterxml/jackson/core/jackson-annotations/2.9.0/jackson-annotations-2.9.0.jar, ignoring it[I 07:38:12.309 NotebookApp] KernelRestarter: restarting kernel (4/5), new random ports
Error while downloading https://repo1.maven.org/maven2/co/fs2/fs2-core_2.12/2.0.0/fs2-core_2.12-2.0.0.jar: Ongoing concurrent download for https://repo1.maven.org/maven2/co/fs2/fs2-core_2.12/2.0.0/fs2-core_2.12-2.0.0.jar, ignoring it
[W 07:38:15.321 NotebookApp] KernelRestarter: restart failed
[W 07:38:15.321 NotebookApp] Kernel b279ce9d-2d6a-4f79-8da0-3de1b65cb2d9 died, removing from map.
```

how amenable would the project be to relaxing these conditions to afford for use cases where the assumption of public internet is never true?

**Comment by alexarchambault** [comment]
@kwlzn Passing `--standalone` to the `coursier bootstrap` command [when creating a launcher](https://almond.sh/docs/quick-start-install.html#create-a-launcher) creates a launcher that doesn't need to download anything to start, which should solve the `Error while downloading` messages you're seeing.

The resulting installation seems to work, but I can't recall whether there were issues down-the-line when passing that option.

**Comment by kwlzn** [comment]
@alexarchambault rad, thanks for the tip! I'm now able to launch the kernel behind the firewall.

now, when I run e.g.:

```
import $ivy.`org.apache.spark::spark-sql:2.4.0`
```

in a new kernel, it attempts to fetch from maven central first and after a lengthy (~minutes) timeout per fetch it does end up eventually hitting the repo I defined with `--extra-repository`. but it's significantly slower than e.g. in a Docker container due to the compound wait for the timeout.

**Comment by alexarchambault** [comment]
I didn't try, but something like
```scala
import coursierapi.MavenRepository
interp.repositories() = Seq(
  MavenRepository("https://…your-repository…")
)
```
in a separate cell, prior to the cells doing the `import $ivy`, ought to work.

**Comment by frgomes** [comment]
@kwlzn Maybe a shell script I've made may be of your interest.
It automagically installs Coursier, Almond and Jupyter.

https://github.com/frgomes/bash-scripts/blob/master/user-install/install-jupyter.sh

**Comment by kwlzn** [comment]
setting `interp.repositories()` did the trick! thanks for the pointer. we've got this packaged up nicely now w/ a predef that we can drop into our offline notebook. really appreciate the help.

**Comment by firefoxwang** [comment]
Now just download coursier and set your [Repositories](https://get-coursier.io/docs/other-repositories), for example(my env use git bash on windows ):
1. download coursier from an online computer then move it to the offline one
`curl -fLo coursier https://github.com/coursier/launchers/raw/master/coursier`  
2. set repo env in git bash on an offline computer
`export COURSIER_REPOSITORIES="ivy2Local|https://…your-repository…" `  
3. create a  launcher  in bash   
`./coursier launch --fork almond:0.10.0 --scala 2.12.11 -- --install`    
4. run jupyter in the same bash   
`jupyter notebook `  

if you use jupyter notebook in another bash(without `COURSIER_REPOSITORIES` env variable),just past the code below before `import $ivy`:  
```python
import coursierapi.MavenRepository  
interp.repositories()  =List(MavenRepository.of("https://…your-repository…/"))   
```
