### ISSUE TITLE
Almond 0.9.1 with Scala 2.13.1 fails to install dependencies on Windows 10

### ISSUE THREAD

**Issue by sheldon1iu** [almond-sh/almond#533]
![image](https://user-images.githubusercontent.com/39169452/77990015-cf42de80-7352-11ea-99a5-8b058beaa1f8.png)

It is worth noting that my almond is compiled on centos 7 because the releases Amond 0.9.1 don't work for me and the cert cause I cant compile it on Windows 10.

**Comment by alexarchambault** [comment]
The suffix you're seeing (`_2.13`) stands for scala `2.13.x`. It's added to the name of libraries, and means that library targets scala `2.13.x`.

Not finding the library then means either the library you're looking is malformed (wrong name, wrong version, …), or isn't published for that scala version. In the case you're describing, I think it's the latter, tensorflow-scala not being published for scala `2.13`. It's only published for scala `2.11` and `2.12` AFAIK.

Installing almond for scala `2.12` should fix that.

**Comment by sheldon1iu** [comment]
> The suffix you're seeing (`_2.13`) stands for scala `2.13.x`. It's added to the name of libraries, and means that library targets scala `2.13.x`.
> 
> Not finding the library then means either the library you're looking is malformed (wrong name, wrong version, …), or isn't published for that scala version. In the case you're describing, I think it's the latter, tensorflow-scala not being published for scala `2.13`. It's only published for scala `2.11` and `2.12` AFAIK.
> 
> Installing almond for scala `2.12` should fix that.

Thanks for your reply.
I tested  a another dependency and browsed path of the dependency in maven repo,but the result semms to be more biased towards the former.
 
![image](https://user-images.githubusercontent.com/39169452/78029157-b5c18700-7392-11ea-8a8f-1c540a81d5a2.png)
![image](https://user-images.githubusercontent.com/39169452/78029366-0a650200-7393-11ea-9d1a-a99e04b449e0.png)
![image](https://user-images.githubusercontent.com/39169452/78029938-ee159500-7393-11ea-8e27-f2ec5a64aa93.png)
![image](https://user-images.githubusercontent.com/39169452/78030095-26b56e80-7394-11ea-902e-884db55bc90b.png)

**Comment by alexarchambault** [comment]
These libraries (`commons-codec`, `httpcomponents`) are Java libraries, not scala ones. They should be imported with single ':', like
```scala
import $ivy.`commons-codec:commons-codec:1.14`
```

**Comment by sheldon1iu** [comment]
It is useful,thank you very much.It solved my problem.
