### ISSUE TITLE
how to load `CompilerPlugin` 

### ISSUE THREAD

**Issue by jijingg** [almond-sh/almond#540]
my build.sbt is 
```scala 
libraryDependencies ++= Seq(
  "com.github.spinalhdl" % "spinalhdl-core_2.11" % "1.4.0",
  "com.github.spinalhdl" % "spinalhdl-lib_2.11"  % "1.4.0",
   compilerPlugin("com.github.spinalhdl" % "spinalhdl-idsl-plugin_2.11" % "1.4.0")
)
```
in Jupyter i can load the first two line like this :
```scala
import $ivy.`com.github.spinalhdl::spinalhdl-core:1.4.0`
import $ivy.`com.github.spinalhdl::spinalhdl-lib:1.4.0`
```
but i m' not sure how to import the third line 
`compilerPlugin("com.github.spinalhdl" % "spinalhdl-idsl-plugin_2.11" % "1.4.0")`

**Comment by sbrunk** [comment]
This is described in the ammonite-api docs: https://almond.sh/docs/api-ammonite.html#load-compiler-plugins

**Comment by jijingg** [comment]
@sbrunk thanks, it's work,
instead `compilerPlugin("com.github.spinalhdl" % "spinalhdl-idsl-plugin_2.11" % "1.4.0")` by
`import $plugin.$ivy.`com.github.spinalhdl::spinalhdl-idsl-plugin:1.4.0``
