### ISSUE TITLE
Ivy import uses wrong Scala version, causing it to fail

### ISSUE THREAD

**Issue by abhay-agarwal** [almond-sh/almond#607]
I am attempting to use Almond-Spark. I have installed Almond `0.6.0` with Scala `2.11` using the following command: 

`./coursier launch almond:0.6.0 --scala 2.11 -- --jupyter-path /opt/conda/anaconda/share/jupyte
r/kernels --install`

However, when I attempt to import `almond-spark` from Jupyter I receive the following error: 

```
import $ivy.`org.apache.spark::spark-sql:2.3.4` // Or use any other 2.x version here
import $ivy.`sh.almond::almond-spark:0.6.0` // Not required since almond 0.7.0 (will be automatically added when importing spark)

Failed to resolve ivy dependencies:Error downloading sh.almond:almond-spark_2.13:0.6.0
  not found: /root/.ivy2/local/sh.almond/almond-spark_2.13/0.6.0/ivys/ivy.xml
  not found: https://repo1.maven.org/maven2/sh/almond/almond-spark_2.13/0.6.0/almond-spark_2.13-0.6.0.pom
```

It looks like it is using the wrong version of Scala (`2.13`) from my version (`2.11`). I can confirm that Maven resolves if provided the correct Scala version by going to https://repo1.maven.org/maven2/sh/almond/almond-spark_2.11/0.6.0/almond-spark_2.11-0.6.0.pom and seeing a resolved XML file.

**Comment by alexarchambault** [comment]
It's kind of surprising that it tries to fetch 2.13 artifacts...

We dropped scala 2.11 support a while ago though, when [Ammonite](https://github.com/lihaoyi/Ammonite), that we rely on, dropped it. Would it be a possibility for you to switch to scala 2.12? That would allow to use the latest almond version (`0.10.1`).

**Comment by abhay-agarwal** [comment]
Hmm, it seems to work now! It must have been some kind of caching or memory issue.
