### ISSUE TITLE
Adapting from protocol version 5.1 (kernel ...) to 5.3 (client).

### ISSUE THREAD

**Issue by seddonm1** [almond-sh/almond#626]
Is it possible to update to meet the 5.3 protocol version so we don't get these 
```Adapting from protocol version 5.1 (kernel ) to 5.3 (client).``` 
messages in the logs?

**Comment by alexarchambault** [comment]
I've been finding those annoying too… One should take the time to go through what changed between `5.1` and `5.3`, ensure everything's fine, and bump the version [here](https://github.com/almond-sh/almond/blob/3e8793203060f3d415f56010091b977bcf762732/modules/shared/protocol/src/main/scala/almond/protocol/Protocol.scala#L4-L5).

**Comment by seddonm1** [comment]
It doesn't look like there are major breaking changes based on the changelog: https://jupyter-client.readthedocs.io/en/stable/changelog.html so i'll have a go of building 5.3 locally and seeing if anything breaks.

**Comment by seddonm1** [comment]
I have replaced `protocol_2.12-0.10.4.jar` with a new version with the version set to `5.3`. No negatives appear to have been caused and the `Adapting from protocol` is no longer present.

**Comment by sbrunk** [comment]
@seddonm1 would you like to create a PR bumping the version then?

**Comment by seddonm1** [comment]
perhaps @alexarchambault could build a 0.11.0 release candidate and we can test it more thoroughly?

**Comment by alexarchambault** [comment]
Just tagged `0.10.5` which sends `5.4` as message protocol.

**Comment by seddonm1** [comment]
Thanks alex
