### ISSUE TITLE
Unable to turn off ammonite colors

### ISSUE THREAD

**Issue by bhoward** [almond-sh/almond#635]
It is supposed to be possible to turn off the ANSI color codes in ammonite output with `interp.colors() = ammonite.util.Colors.BlackWhite`, but that doesn't seem to have any effect from within Jupyter (no errors, it just doesn't turn off the color). Tried from both a notebook cell (Jupyter Lab) and passing `--predef-code` when starting the kernel. It does work from an ammonite REPL. Almond version 0.10.5.

**Comment by bcdroid** [comment]
As another data point, that line did work to turn off colors that were showing as escape sequences from within Emacs with Emacs IPython Notebook (ein) with Almond as kernel.  Thanks!
