### ISSUE TITLE
Inconsistent results between jupyter-scala and the scala REPL

### ISSUE THREAD

**Issue by sbromberger** [almond-sh/almond#72]
On jupyter-scala:

```
def foo(x:Int)(y:Int) = x+y
val y: Int=>Int = foo(5)
```

returns an error:

```
Main.scala:26: type mismatch;
 found   : () => Int => Int
 required: Int => Int
}.apply
  ^
```

However, this is valid scala and works in the repl.

**Comment by alexarchambault** [comment]
Thanks for the report. As a workaround, the following is fine:
```scala
def foo(x:Int)(y:Int) = x+y
val y: Int=>Int = foo(5)(_)
```

**Comment by alexarchambault** [comment]
Works fine with the current master (and all releases under the "almond" name should be fine too).
