### ISSUE TITLE
Installing almond to /usr/share/jupyterlab (ie. for all users) doesn't work

### ISSUE THREAD

**Issue by qbouvet** [almond-sh/almond#729]
Hi, 

I want to install almond to use it in jupyterlab. I would like to install it for all user. Unfortunately, I can't get it to work. 

## The issue

I want to install almond it to ```/usr/share/jupyter/kernels```, instead of installing to ```~/.local/share/jupyter/kernels/scala``` for a single user. My other kernels (like python3) are indeed located in ```/usr/share/jupyter/kernels``` and work fine. So, I install almond with the following command: 

    $ sudo coursier launch --fork almond:0.10.9 --scala 2.13.1 -- --install --jupyter-path /usr/share/jupyter/kernels/
    >>> ... downloads ...
    >>> Installed scala kernel under /usr/share/jupyter/kernels/scala

After that, I can start jupyter-lab and the option to create a scala notebook indeed appears. If I create a notebook, the kernel fails to connect (status "Connecting", then "Disconnected"  at the bottom left of the web interface). In the console, I have the following error messages: 

    [I 2021-01-28 16:47:11.133 ServerApp] Kernel started: b1c696f1-0ac7-4096-8733-21d2c6907b21
    Error: class almond.ScalaKernel not found
    [I 2021-01-28 16:47:14.135 ServerApp] KernelRestarter: restarting kernel (1/5), new random ports
    Error: class almond.ScalaKernel not found
    [ ... 4 more times]

What is weird is that almond works perfectly if I install it for one user with: 

    $ coursier launch --fork almond:0.10.9 --scala 2.13.1 -- --install
    >>> Installed scala kernel under $HOME/.local/share/jupyter/kernels/scala

## Why does it matter ?

The big picture is that I am trying to fix the [almond package](https://aur.archlinux.org/packages/almond/) for arch linux. When packaging, one must install in /usr/local which is the standard location for packages that all users have access to.

## System

Kernel: linux-5.4.92-1-lts
Java: Oracle JDK 11 (also tried with Oracle JDK 8)
Coursier: 2.0.7, JVM version from the AUR (although I also tried with 2.0.9 native version from [get-coursier](https://get-coursier.io/docs/cli-installation.html#native-launcher))

---

Could you help me out with this ? Let me know if you need any additional info

Best

**Comment by potoo0** [comment]
Got some problem.

**Comment by potoo0** [comment]
`Error: class almond.ScalaKernel not found`, just because cache path was not specified during installation, so it will use default cache path [`~/.cache/coursier/v1`](https://get-coursier.io/docs/cache.html#default-location), so other users will not find the jar in the cache path.
> open launcher.jar/coursier/bootstrap/launcher/bootstrap-jar-urls will find:
> file:<coursier cache path>/https/jitpack.io...

So, if we want to install global, must override cache path.

demo:
```
# create folder for global cache
mkdir /usr/share/coursier/cache
# add to bashrc for all users who want to use kernel
export COURSIER_CACHE=/usr/share/coursier/cache

# install kernel
coursier launch --fork almond:0.10.0 --scala 2.12.11 -- --install --global

# change perm for all users who want to use kernel, let's say jupyter group
chgrp -R jupyter /usr/share/coursier
chmod -R g+rwxs /usr/share/coursier

# add kernel read perm for user
chmod -R +r /usr/local/share/jupyter/kernels/scala
```

**Comment by qbouvet** [comment]
The solution does work. Closing.
