### ISSUE TITLE
Document how to generate the launcher

### ISSUE THREAD

**Issue by sciabarra** [almond-sh/almond#83]
I am trying to recreate the installer from sources but it is not documented - the documentation refers to the cli/packArchive (that should be scala-cli/packArchive) that appears to be obsoleted and do not work. It would be awesome also to document how to add extra dependencies, in order to build a version of the kernel including for example spark.

**Comment by alexarchambault** [comment]
It can be generated by running `project/generate-launcher.sh`. You can set the version of jupyter-scala it should use in the script, and run it with the `--2.10` option to generate a scala 2.10 kernel launcher. About the spark support, it can't really be included in the launcher - the kernel itself isn't included in it. The launcher only knows the URLs where to download the launcher artifacts. The spark support is added to the kernel on-the-fly, as shown at https://github.com/alexarchambault/ammonium#spark.

**Comment by sciabarra** [comment]
this is a significant problem - I need to provide the spark support out-of-the box for my use case, like toree and zeppelin

**Comment by alexarchambault** [comment]
It *is* supported. One just has to type a few lines to use spark.

I have small libraries and enhancements to come that make that easier, but for now, these have to be manually entered.

**Comment by sciabarra** [comment]
Thank you so much I think this issue can be closed. On a side note, I tried to add extra dependencies with -I, editing the generate-launcher.sh script but it does not seem to include in the launcher the other dependencies. Should I instead add the dependency to build.sbt?

**Comment by alexarchambault** [comment]
With the very last version (download directly the launcher via the `jupyter-scala` file on https://github.com/alexarchambault/jupyter-scala), these can be added on start up via the `-d` option (like `jupyter-scala --id scala-test --name "Scala (test)" -d org:name:version -r extra-repo`).

You're one of a few people now to ask for explanations about the launcher... Promising I will update the doc in the coming days, with more explanations...

**Comment by alexarchambault** [comment]
I updated the README with [special instructions](https://github.com/alexarchambault/jupyter-scala#compiling-it) about how to compile it locally, and also how to build standalone launchers, in case you modify the sources.

**Comment by alexarchambault** [comment]
Generating a launcher is the main way of installing the kernel (since the rename to "almond"), see the website (link in README).
