### ISSUE TITLE
Kernel install failure. Cannot find default main class. [Linux]

### ISSUE THREAD

**Issue by notmike-5** [almond-sh/almond#835]
I have been attempting to install almond on linux by following the instructions found at: [https://almond.sh/docs/quick-start-install](https://almond.sh/docs/quick-start-install)

(1) Running the command `./coursier launch --fork almond -- --install` results in the error:

`Cannot find default main class. Specify one with -M or --main-class.`

(2) Running again as `./coursier launch --fork almond -M almond.ScalaKernel -- --install` reports:

`Installed scala kernel under /home/myuser/.local/share/jupyter/kernels/scala`

After (2) I do see a scala kernel option in Jupyter, but clicking it results in a `500 Internal Server Error`.

==> Kernel install failure.

**Comment by kwalcock** [comment]
The same missing main class is reported under Windows for both the --install and --help commands:
```
PS D:\Users\me\coursier> ./coursier launch --fork almond -- --help
Cannot find default main class. Specify one with -M or --main-class.
```

If I add the `-M almond.ScalaKernel` for the `--install`, it seems to hang.

**Comment by ItoYo16u** [comment]
Did you try -v option to get details?

https://get-coursier.io/docs/cli-launch

**Comment by kwalcock** [comment]
I'm not sure why the downloaded coursier file that results from `https://almond.sh/docs/quick-start-install` would be partly text and partly what looks like a zip file.  There is no -v.

```
> coursier -v launch --fork almond -- --install
Unrecognized argument: -v
```

**Comment by ItoYo16u** [comment]
Pass `-v` option like this.
```
cs launch --fork almond -v -v
```
Besides, did you try  `curl -Lo coursier https://git.io/coursier-cli-"$(uname | tr LD ld)"` instead of `curl -Lo coursier https://git.io/coursier-cli` when install coursier cli ?

**Comment by ItoYo16u** [comment]
> I'm not sure why the downloaded coursier file that results from curl -Lo coursier https://git.io/coursier-cli as instructed at https://almond.sh/docs/quick-start-install would be partly text and partly what looks like a zip file

The curl command fetches executable.
If you want to just run coursier,
```
curl -fLo coursier https://git.io/coursier-cli-"$(uname | tr LD ld)"
chmod +x coursier
./coursier <command>
```

https://get-coursier.io/docs/cli-installation

If you want to install coursier  and  then run it via cs command.
```
curl -fLo coursier https://git.io/coursier-cli-"$(uname | tr LD ld)"
chmod +x coursier
./coursier install cs
cs <command>
```

**Comment by kwalcock** [comment]
I tried 11.1 and 11.0.  They seemed to download and then just hang.  Jupyter never noticed a scala kernel.

**Comment by ItoYo16u** [comment]
@kwalcock

Ok, what Java version do you use? Run `Java --version`.
If Java is not installed,

```shell
cs java --jvm adopt:11 --setup
# Setup Path and restart bash.
cs launch almond:0.11.0 --scala 2.13.4 -- --install --id scala213 --display-name "Scala (2.13)" 
cs launch almond:0.11.0 --scala 2.12.12 -- --install --id scala212 --display-name "Scala (2.12)"
```

**Comment by kwalcock** [comment]
A more accurate `java -version` gives `1.8.0_181` which is what otherwise runs scala and sbt on the machine and is used with IntelliJ without problem.  Several other versions are installed, but not configured.  Why are you restarting bash on Windows?  I can just install it on my Linux machine or in a VM, but that isn't the point.

**Comment by notmike-5** [comment]
@ItoYo16u
I ran `./coursier launch --fork almond:0.11.1 -- --install --force` given your suggestion. It installs a kernel in `/home/user/.local/share/jupyter/kernels/scala` that jupyter can see.

However, when I go into jupyter to start a new scala notebook I get `500: Internal Server Error` and jupyter seems to suggest a permissions error?

`[E 16:45:58.712 NotebookApp] Uncaught exception GET /notebooks/Untitled3.ipynb?kernel_name=scala (127.0.0.1)
    HTTPServerRequest(protocol='http', host='localhost:8888', method='GET', uri='/notebooks/Untitled3.ipynb?kernel_name=scala', version='HTTP/1.1', remote_ip='127.0.0.1')

{some stack trace}

PermissionError: [Errno 13] Permission denied: '/usr/local/share/jupyter/nbconvert/templates/conf.json'

{some stuff about the agent}

[E 16:45:58.715 NotebookApp] 500 GET /notebooks/Untitled3.ipynb?kernel_name=scala (127.0.0.1) 97.270000ms referer=http://localhost:8888/tree`
