### ISSUE TITLE
cli/packArchive not working on Windows 10

### ISSUE THREAD

**Issue by Johnnyboycurtis** [almond-sh/almond#84]
I recieve the following error when trying to compile the scala kernel through the "sbt cli/packArchive" command.

Jonathan@Jonathan-PC MINGW64 ~/jupyter-scala (master)
$ sbt cli/packArchive
[info] Loading project definition from C:\Users\Jonathan\jupyter-scala\project
[info] Set current project to jupyter-scala (in build file:/C:/Users/Jonathan/jupyter-scala/)
[error] Expected ID character
[error] Not a valid command: cli (similar: alias, plugin)
[error] Expected project ID
[error] Expected configuration
[error] Expected ':' (if selecting a configuration)
[error] Expected key
[error] Not a valid key: cli (similar: clean, doc)
[error] cli/packArchive
[error]    ^

Any assistance would be great!

**Comment by alexarchambault** [comment]
A bit long to explain straightaway. I'll (really) update the doc in the coming days.

**Comment by alexarchambault** [comment]
I updated the README with instructions about that: https://github.com/alexarchambault/jupyter-scala#compiling-it.
