### ISSUE TITLE
Importing notebook from other notebook

### ISSUE THREAD

**Issue by kornelc** [almond-sh/almond#906]
Hello,

I have a quick question regarding importing common code that sets up the environment for my notebooks:

The import $file.<filename> directive works great for .sc files, but is it possible to include a notebook from another notebook, kind of like what the %run <subnotebookfile.ipynb> magic does in the Python world.

Basically, I would like to be able to edit the included files easily through the Jupyter UI, just like I can do it with notebooks, and if its an .sc file, I cannot easily edit it through the web UI from what I can tell. Or is there a way to edit .sc file through the UI as well?

**Comment by kiendang** [comment]
Yes you can edit `.sc` files or any text file with either Jupyterlab or the classic Jupyter notebook UI.

**Comment by kiendang** [comment]
Or if you prefer to edit code in a notebook I would suggest just do that, then save it as a `.sc` file using `nbconvert --to script` then you can import it into another notebook. Straight up importing notebooks from another notebook is generally a bad idea.

**Comment by kornelc** [comment]
@kiendang Thanks for the quick response! I was able to edit the .sc files as you said, which was the main thing I was after. So my main problem is solved now!

> Straight up importing notebooks from another notebook is generally a bad idea.

I'm curious, what problems do you see with importing notebooks from other notebooks. I'm asking because we have a big part of our infrastructure for data scientists implemented as Databricks Scala notebooks, which form a hierarchy, that seems to work well for us. So that is why I was looking to see if the same thing is doable with Almond. 

Consider these three notebooks that implement overnight jobs:
notebook-to-import-data
  import notebook-to-import-data-from-source1.
  import notebook-to-import-data-from-source2.

Then you schedule the top notebook to run from chron overnight. Separate devs can work on each sub-notebook. Then in the morning  after the run, you can look at each notebook output to see what actually happened. It seems it would be useful to implement functionality to import notebooks for this kind of scenario.

Almond has such a powerful API, especially for importing. Is there something I can do relatively easily, like write some extension code/plugin/other extra code, that would allow me to implement notebook import if it doesn't yet exist?

**Comment by kiendang** [comment]
> Thanks for the quick response! I was able to edit the .sc files as you said, which was the main thing I was after. So my main problem is solved now!

Great!

> I'm curious, what problems do you see with importing notebooks from other notebooks. I'm asking because we have a big part of our infrastructure for data scientists implemented as Databricks Scala notebooks, which form a hierarchy, that seems to work well for us. So that is why I was looking to see if the same thing is doable with Almond. 

Oh sorry that was what I got from my personal experience (which resembles what's mentioned in this [talk](https://www.youtube.com/watch?v=7jiPeIFXb6U)), by no means a criticism. Glad to learn about your use case where importing notebooks works.

> Almond has such a powerful API, especially for importing. Is there something I can do relatively easily, like write some extension code/plugin/other extra code, that would allow me to implement notebook import if it doesn't yet exist?

I'm not sure myself since I'm unfamiliar with how importing notebooks was implemented in Python kernels.
