### ISSUE TITLE
Installation on Windows fails - "cannot find default main class"

### ISSUE THREAD

**Issue by nyambol** [almond-sh/almond#911]
Hello,

`coursier launch --fork almond -- --install`

    [ ... ]
    100.0% [##########] 197.8 KiB (2.0 MiB / s)
     https://repo1.maven.org/maven2/org/typelevel/cats-kernel_2.13/2.5.0/cats-kernel_2.13-2.5.0.jar
    100.0% [##########] 5.0 MiB (4.1 MiB / s)
     https://repo1.maven.org/maven2/org/scala-lang/scala-library/2.13.5/scala-library-2.13.5.jar
    100.0% [##########] 5.6 MiB (2.5 MiB / s)
    https://repo1.maven.org/maven2/org/scala-lang/scala-compiler/2.13.4/scala-compiler-2.13.4.jar
    100.0% [##########] 11.1 MiB (5.0 MiB / s)
     Cannot find default main class. Specify one with -M or --main-class.

Windows 10
Java 17

I installed coursier with the Windows installer from their site.

Thanks.
mp

**Comment by hmf** [comment]
@nyambol 

Try:

`./coursier launch --fork almond -M almond.ScalaKernel -- --install`

See https://github.com/almond-sh/almond/issues/835

**Comment by epsi95** [comment]
`.\coursier launch --fork almond -M almond.ScalaKernel -- --install` worked for me

**Comment by richardle91** [comment]
Exception in thread "Thread-0" java.nio.file.FileSystemException: C:\Users\Richard\AppData\Local\Temp\coursier-launch-7197478231790172675.jar: The process cannot access the file because it is being used by another process.

Every time I go to install this it hangs? and when I terminate this is the error I see

**Comment by alexarchambault** [comment]
@nyambol You might need a more recent version of the coursier launcher. Some old versions had issues finding its main class.
