### ISSUE TITLE
Loading .jar file

### ISSUE THREAD

**Issue by dbl001** [almond-sh/almond#96]
How do I load .jar dependencies?

classpath.addPath() doesn't seem to work.
classpath.addPath("/home/ubuntu/aas/ch06-lsa/target/ch06-lsa-1.0.2-jar-with-dependencies.jar")

neither did load.jar()
![screen shot 2016-07-23 at 8 54 51 pm](https://cloud.githubusercontent.com/assets/3105499/17081709/be014654-5117-11e6-87a3-a8cb132405cf.png)

load.jar("/home/ubuntu/aas/ch06-lsa/target/ch06-lsa-1.0.2-jar-with-dependencies.jar")

**Comment by dazebug** [comment]
```scala
import ammonite._, ammonite.ops._
val jars = ls! root/'target/'pack/'lib |? (_.ext == "jar")
jars.map(interp.load.cp(_))
```
works (but it is far slower than `classpath.addPath`)

**Comment by dazebug** [comment]
Does anybody know how make :point_up_2: faster?

**Comment by captify-nzavgorodnii** [comment]
This worked for me (on macOS):
```
val path = java.nio.file.FileSystems.getDefault().getPath("/Users/username/foo/bar/somefilename-1.170620.0.jar")
val x = ammonite.ops.Path(path)
interp.load.cp(x)
import com.companyname.classname```

**Comment by nikitajz** [comment]
This worked for me (on macOS):
```
val path = java.nio.file.FileSystems.getDefault().getPath("/Users/username/foo/bar/somefilename-1.170620.0.jar")
val x = ammonite.ops.Path(path)
interp.load.cp(x)
import com.companyname.classname
```

**Comment by alexarchambault** [comment]
This now works exactly as in [Ammonite](http://ammonite.io/#Ammonite-REPL), whose `interp.load.cp` and `import $cp. ...` should work here.
